### ISSUE TITLE
utf-8" prefix on filenames when sending through smtp directly

### ISSUE THREAD

**Issue by doebi** [ProtonMail/go-proton-api#114]
When sending mail throught the smtp connection, the file attachments have the prefix utf8" on their filename.

![2023-10-19_12-43](https://github.com/ProtonMail/go-proton-api/assets/1591457/52142a6d-db53-495a-a74a-625b1d7c46ca)

I send mails through this service:
https://github.com/ddvk/rmfakecloud

The corresponding line of code is found here: 
https://github.com/ddvk/rmfakecloud/blob/master/internal/email/smtp.go#L84

The utf-8 prefix is based on RFC, a stackoverflow thread related to this: https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

**Comment by LBeernaertProton** [comment]
go-proton-api by itself does not contain any SMTP server. Please open a ticket in the relevant project or contact proton customer support.
